name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build and Test Docker Image
      run: |
        docker build -t todolist:latest .
        docker run -d --name todolist-container todolist:latest java -jar /app.jar --version

    - name: Stop and Remove Docker Container
      run: |
       docker stop todolist-container
       docker rm todolist-container
